sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull muccg/ccg-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- ./travis-build.sh

env:
  global:
    - DOCKER_USERNAME: ccgbuildbot
    - secure: "XtuIpIUtc4+VPLDoFp1Qoc/CYN5AiSgOgOR7SlPtBZbLy1WTjdX8myIZUu2cuFgf6QXSrIeAXDqa0VEeC5Or5E8dKwM2PSQ81khVSbZQxNPY19n4B5bCz3c1GcSTN9ycRhVjmy86Cj1L3MJtjl8sKm2ngYn8YdHl2dYs236WS0Ens+hBUIAY+m/H/VbXJqyvF8OTV9in44TzLF1u0AY0OwXjH/TMmbki6dgv3ByPa3Qvw2Cy7rl/Z77M411F8AkYe0NkcaAnD88eQwZTFgU3sNXPwtcLINZwyQAeD86UnODblujh3AI/rkfQ2c3Nmy2RUly+KQWGWMoiUL1x3yter5VqeBmqLfbhs6AnspLwZiIujejx7+Z5PRD+9OHOGMGgFmzYXdtofxvOSOI2/g5atXlmLUL+gflm4+ULMRi+z6xIdOYD4kmFI8yMbKrTsGFcJLUVz0z0KxJfDmkXXq7uM8zB2dvFqOvhuerWoVwd3g9zx7fc2IF8tTcDY9T2S5HJ691dMhGkmSelN9ttiG1/kubAuakyqtnzLtZqIWbtnrvflgR3Y6SuIwJ2K9g3P3uaqBNrpSV4SWbGhSkwunza1wuL31aH5hgihZmzrUvSRRe3Z2BcjYDcgaefUFqjDcCsEpBjGer81kPhsgMre+R/WOJUAX1k/C+K3ZU7fvl6Tv0="
