sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull muccg/ccg-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- "./travis-build.sh"
env:
  global:
  - DOCKER_USERNAME: devredbox
  - secure: D0wLmo83jkM4vP+5yResjfuNYpuiho+ulmGOLcdKHKORyro2ilHaPG4VSjH+Mtn6STSEqeANLzGsB4YfKhVj7IoDHGQqmwx7P4wGv8ItBiJMkmpuOW4y/3WtZoOj8xnkDjKJkWlqHzqUxAt+hbmvuERzBMeXT9M8J0usMdxoJ2a1FKYg/AoMMsQp7TkzhagooBmPTHlNEs5DBswvhobZ6z5CF9F/TDgV3WEwWVe1hQLUB7UphCQ8s8hKjkf1Loarr5h/++sKf6gair+eHlpFyok8AHgkr1TWkAKeEsJ6s3X7qNocXstQyrYfh4+uTOtD85KyuQ8goc4UybgRoQKfhRopuynEO+81UTo6Ur7asGCs0JrKUmB3QiLm6jo+n7n+mAu1n3n8pDIu41P5acrj+jqh5vumKnPOh5Rv5DjyO/xxf5MN/ppnbNOknjZ+58yPjISjYiVoWPSqThtGhXG/JF7AK3RVJYmVv8BQ8h0MloNfvs3I9f0+ofSSGwhOJIUsVKzUDxo+EDR/VBMrcPB4au3Qcgh2psttiysD/fqEQDjjj7wK9ewRydcTiw3voz3j3eNbLzYzSjsNpgbpB2VBYXsVGq9+cYYUJ1MKJBH/QAtPTOu883sI8S/BIALAw+0tuy6EQs8DX84coCnF7Nq56a5cb+b/CqKodPNbKxQ3Wvc=
