sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull muccg/ccg-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- ./travis-build.sh

env:
  global:
    - DOCKER_USERNAME: gbowland
    - secure: "pAl9upK+1SjX6NRsPYDGXnvoT4AxKF0fUh9xUXozGni5ZTF58Es8b3/AePC/sDG1gCrHeu6xYucoe6eu6KWUJs8buzGc5+WawE9/CmWlEJ/6Oxj73c93cVpBh9Iao9pW9wZZ8fp8c/OL9ehJUDV/d9dZp4LQUCmJrVjG9fqWIVsGC13HxSxuz9z4rxlzrdpeeD6v6zpAuv//wyNawr3CSrs8ySuO3eGCt6hnlyUe1P/VsypQiruGHhCUwXdy/6hlFhEyhxTHMVIGCocBoLXxcxR/UxHbJKFNINMoW7TeeT182UeUHHyS+wYWLNdoNWtmnf9ZM6LJ4BZpu61ZLd8nQZ4D5AAwFE6I6li9oM0TweJxvcHnxaESvO+BNp2rWULdLpCc80I/aDf+oZy+UTXajHmxd/z81a8JMtGI1qQAOIEecNAGNFarLVa/A00d7UrzkUDxIV1OCAu4PFRfFVJaYCwh81XmRLJAtlRJianQtwmKyd8xUiE7L/kihufxCItuFrX9Bi0b41ArzRyrGtO0PX7jQ+rkhxaYcElM7YE62yAjvk0jwYXyZrWlq/57oUgGG8B2D/H/qlvkgENUWrX4KXebY20fx5HmsISDhf/Ldl+j8/3j+DIiZMI+/qnNKaoB5FqOgk4yI5jvqHs34tLFxmCF8eyClOUql7gC8csEfmk="
